name = "markdownswatch-examples"
account_id = "9bd4e309172b11e0c555e45fbd05bd92"
workers_dev = true

compatibility_date = "2023-10-30"
main = "server.ts"
env = {}

[[kv_namespaces]]
binding = "MDS_SWATCH_PUBLIC_KV"
id = "ddc8daa599834b518361afe68fcef912"

[site]
bucket = "./public"
